### ISSUE TITLE
iTerm's icon is low res.

### ISSUE THREAD

**Issue by tkodev** [ealeksandrov/cdto#3]
This is from the 2.8 release. I'm on the 2016 Macbook Pro display.
![screen shot 2017-08-09 at 10 04 11 am](https://user-images.githubusercontent.com/4338187/29125557-199f02c2-7cea-11e7-96f8-2d8ee38f22eb.png)

Is there a way to get non blurred toolbar icons / are there self build instructions for this application?

**Comment by ealeksandrov** [comment]
I think it's good for me?
![screen shot 2017-08-13 at 14 13 44](https://user-images.githubusercontent.com/3132438/29249098-acc57cda-8031-11e7-81ee-d32a4b390ae8.png)

Anyway, I'll look more closely into it later.

Self build instructions:
1. Choose "cd_to all" scheme
2. Build&Archive
3. Export
4. Save built products

**Comment by tkodev** [comment]
Thanks I'll give it a go 👍

**Comment by tkodev** [comment]
![screen shot 2017-08-14 at 5 16 01 pm](https://user-images.githubusercontent.com/4338187/29292212-44cf8a92-8114-11e7-81c0-f596a9f3a098.png)

I updated the `icons.icns` file to include assets up to 1024px. Not sure if it looks alright on low resolutions but the pull request is here if you like :) https://github.com/ealeksandrov/cdto/pull/4
