### ISSUE TITLE
document difference between this fork and the original version

### ISSUE THREAD

**Issue by marc-guenther** [ealeksandrov/cdto#8]
Both this and the  jbtule/cdto are available in Homebrew on Mac for example. It is entirely unclear which one to choose and what is the difference between the two.

**Comment by ealeksandrov** [comment]
Right, I need to check latest updates in `jbtule/cdto` and compare to this repo.

Initially I created this fork just to merge outstanding PRs and have built release ready for use. Now since original author is active again there may be less need to maintain a fork.

**Comment by marc-guenther** [comment]
Yea, the huge advantage of Github, it's so easy to create forks. The huge disadvantage of Github, it's so easy to create forks... :)

From what I understand from the README, you added support for iTerm and Hyper?

**Comment by ealeksandrov** [comment]
iTerm was supported by original author, but removed in [v3.0](https://github.com/jbtule/cdto/releases/tag/v3.0) rewrite. This fork was created before removal.
Hyper support added in https://github.com/ealeksandrov/cdto/pull/1.

**Comment by marc-guenther** [comment]
Ah, ok, that might make it more difficult to merge this with upstream.

I use _Terminal_, so I installed version 3.

**Comment by ealeksandrov** [comment]
Here is list of initial changes - https://github.com/jbtule/cdto/issues/25.
Main differences from current jbtule/cdto:
- new icon in this fork
- support for iTerm and Hyper in this fork
- some new settings in original
- code refactoring applied in original

I've tried original 3.1 vs fork 2.8 on Big Sur just now and both work fine, I can't spot any significant difference in performance.

Also I recommend looking at https://github.com/Ji4n1ng/OpenInTerminal - many more integrations and features.
